## Numpy

Импортировать NumPy под именем np

In [39]:
import numpy as np
import math
from scipy import stats
import pandas as pd

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [27]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

Создать вектор размера 10, заполненный единицами

In [26]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

Создать вектор размера 10, заполненный числом 2.5

In [25]:
np.array([2.5]*10)

array([ 2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [24]:
y = np.zeros(10)
y[4] = 1
y

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

Развернуть вектор (первый становится последним)

In [14]:
np.flipud([1,2])

array([2, 1])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [23]:
np.array([[0, 1, 2], [3, 4, 5], [6, 7 ,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [40]:
arr = np.array([1,2,0,0,4,0])
[index for index, elem in enumerate(arr) if elem == 0]

[2, 3, 5]

Создать 3x3 единичную матрицу

In [28]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

Создать массив 3x3x3 со случайными значениями

In [32]:
np.random.random((3, 3, 3))

array([[[  1.32582437e-01,   3.19039751e-01,   6.64729519e-01],
        [  3.61606103e-02,   5.77980515e-01,   9.21925460e-01],
        [  9.03105991e-01,   1.19270805e-01,   1.29569190e-01]],

       [[  2.89879047e-01,   8.19881866e-01,   1.88808424e-01],
        [  8.83159790e-01,   1.61104103e-01,   1.37467854e-01],
        [  3.38039205e-01,   4.19860107e-01,   9.59174079e-01]],

       [[  5.26422567e-01,   3.42698604e-01,   3.61618319e-01],
        [  5.73201691e-01,   7.45258022e-04,   8.13972193e-01],
        [  5.79942380e-01,   2.94039008e-01,   1.52489267e-03]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [34]:
np.mean(np.random.random(30))

0.88666291983256329

Перемножить матрицы 5x3 и 3x2

In [41]:
a = np.random.random((5, 3))
b = np.random.random((3, 2))
np.dot(a, b)

array([[ 0.49940128,  0.21134909],
       [ 1.03140005,  0.9687905 ],
       [ 0.56557442,  0.55794821],
       [ 0.74452044,  0.29600621],
       [ 1.42118556,  0.80085595]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [43]:
np.linspace(0, 1, num=11, endpoint=False)[1:]

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

Заменить максимальный элемент на ноль

In [49]:
a = np.random.random(10)
a

array([ 0.2399803 ,  0.23871871,  0.11937492,  0.4439187 ,  0.65016306,
        0.71341246,  0.89984019,  0.47189554,  0.09650075,  0.04352684])

In [50]:
a[np.argmax(a)] = 0
a

array([ 0.2399803 ,  0.23871871,  0.11937492,  0.4439187 ,  0.65016306,
        0.71341246,  0.        ,  0.47189554,  0.09650075,  0.04352684])

Преобразовать массив из float в int

In [52]:
x = np.random.random(10)
x.astype(int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [25]:
x = np.array([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7], [8, 8], [9, 9], [10, 10]])

In [27]:
distance = []
for i in xrange(len(x) - 1):
    for j in xrange(i + 1, len(x)):
        distance.append(math.sqrt((x[i][0] - x[j][0])**2 + (x[i][1] - x[j][1])**2))

Случайно расположить p элементов в 2D массив

In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9])
np.random.shuffle(arr)
arr.reshape(3,3)

array([[1, 2, 5],
       [4, 3, 9],
       [8, 7, 6]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [24]:
arr = np.array([1, 2, 3, 4, 5])
index = 1
for i in range(len(arr) - 1):
    arr = np.insert(arr, index, [0, 0, 0])
    index = index + 4
arr

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

Найти наиболее частое значение в массиве

In [32]:
arr = np.array([1, 3, 4, 2, 2, 7])
m = stats.mode(arr)
print(m)

ModeResult(mode=array([2]), count=array([2]))


Найти n наибольших значений в массиве

In [38]:
n = 3
arr = [4, 2, 10 ,1 ,5 ,8 ,7 ,6 ,9 ,3]
np.sort(arr)[-n:]

array([ 8,  9, 10])

## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [46]:
food = pd.read_csv("en.openfoodfacts.org.products.tsv", sep="\t")

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Посмотреть первые 5 записей

In [47]:
food.head()

code                                                url  \
0   3087  http://world-en.openfoodfacts.org/product/0000...   
1   4530  http://world-en.openfoodfacts.org/product/0000...   
2   4559  http://world-en.openfoodfacts.org/product/0000...   
3  16087  http://world-en.openfoodfacts.org/product/0000...   
4  16094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [49]:
food.shape[0]

356027

Сколько столбцов в наборе данных?

In [50]:
food.shape[1]

163

Напечатайте все названия столбцов

In [51]:
food.columns.values

array(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity', 'packaging', 'packaging_tags', 'brands',
       'brands_tags', 'categories', 'categories_tags', 'categories_en',
       'origins', 'origins_tags', 'manufacturing_places',
       'manufacturing_places_tags', 'labels', 'labels_tags', 'labels_en',
       'emb_codes', 'emb_codes_tags', 'first_packaging_code_geo', 'cities',
       'cities_tags', 'purchase_places', 'stores', 'countries',
       'countries_tags', 'countries_en', 'ingredients_text', 'allergens',
       'allergens_en', 'traces', 'traces_tags', 'traces_en',
       'serving_size', 'no_nutriments', 'additives_n', 'additives',
       'additives_tags', 'additives_en', 'ingredients_from_palm_oil_n',
       'ingredients_from_palm_oil', 'ingredients_from_palm_oil_tags',
       'ingredients_that_may_be_from_palm_oil_n',
       'ingredients_that_may_be_from_palm_oil',
   

Какое название у 105 столбца?

In [52]:
food.columns.values[104]

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [60]:
food['-glucose_100g'].dtype

dtype('float64')

Как проиндексирован набор данных?

In [61]:
food.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [63]:
food.iloc[18]['product_name']

'Lotus Organic Brown Jasmine Rice'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [64]:
chipo = pd.read_csv("chipotle.tsv", sep="\t")

In [65]:
chipo.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

In [78]:
chipo.shape

(4622, 6)

Как много продуктов стоят более чем $10.00?

In [73]:
chipo['float_item_price'] = chipo.apply(lambda row: float(row.item_price.split('$')[1]), axis=1)

In [77]:
len(chipo[chipo['float_item_price'] > 10.00])

1130

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [80]:
chipo[['item_name', 'item_price']].head()

item_name item_price
0           Chips and Fresh Tomato Salsa     $2.39 
1                                   Izze     $3.39 
2                       Nantucket Nectar     $3.39 
3  Chips and Tomatillo-Green Chili Salsa     $2.39 
4                           Chicken Bowl    $16.98

Отсортировать по имени предмета

In [82]:
sorted_chipo = chipo.sort_values(by=['item_name'])

Сколько было заказано самого дорогого предмета?

In [92]:
most_exp_item_name = chipo.loc[chipo['float_item_price'].idxmax()]['item_name']

In [96]:
chipo[chipo['item_name'] == most_exp_item_name]['quantity'].sum()

130

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [89]:
len(chipo[chipo['item_name'] == 'Veggie Salad Bowl'])

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [99]:
len(chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)])

20